---
- name: playbook-demo
  hosts: all
  remote_user: root
  tasks:
  - name: Instalar librerias necesarias para trabajar
    yum:
      name:
        - git
        - screen
        - nano
        - vim
        - net-tools
        - wget
        - unzip
        - curl
        - nfs-utils
        - bind-utils
      state: present

  - name: Detener servicio firewalld
    systemd:
      state: stopped
      name: firewalld.service

  - name: Deshabilitar servicio firewalld
    systemd:
      name: firewalld.service
      enabled: no
      masked: no

  - name: Deshabilitar SELinux
    selinux:
      state: disabled

  - name: Reiniciar las máquinas para hacer todos los cambios sean efectivos
    reboot:
      reboot_timeout: 120

  - name: Esperar 1 minuto mientras las máquinas inician
    wait_for_connection:
      delay: 30
      timeout: 60
      
  - name: Hacer backup del dnsmasq.conf
    copy:
      src: /etc/dnsmasq.conf
      dest: /etc/dnsmasq.conf.bk
      owner: root
      group: root
      mode: '0644'
      remote_src: yes
      backup: yes

  - name: Eliminar archivo dnsmasq.conf
    file:
      state: absent
      path: "/etc/dnsmasq.conf"

  - name: Crear archivo dnsmasq vacio
    file:
      path: "/etc/dnsmasq.conf"
      state: touch

  - name: Copiar archivo template de dnsmasq al servidor
    template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      
  - name: "Copy File"
    copy: 
      src: /tmp/demofile.txt
      dest: /tmp/demofile.txt

  - name: Iniciar servicio dnsmasq
    systemd:
      state: started
      name: dnsmasq

  - name: Habilitar servicio dnsmasq
    systemd:
      name: dnsmasq
      enabled: yes
      masked: no

  - name: Iniciar servicio haproxy
    systemd:
      state: started
      name: haproxy

  - name: Habilitar servicio haproxy
    systemd:
      name: haproxy
      enabled: yes
      masked: no

- hosts: http.mycluster.example.com
  remote_user: root
  tasks:

  - name: Instalar paquetes para el httpd
    yum:
      name:
        - httpd
      state: present

  - name: Creacion de directorios de httpd para los ignition files y las images de RHCOS
    file:
      path: "{{ item }}"
      state: directory
    with_items:
       - '/var/www/html/ignition'
       - '/var/www/html/images'       

  - name: Reiniciar servicio httpd
    systemd:
      state: restarted
      name: httpd

  - name: Habilitar servicio httpd
    systemd:
      name: httpd
      enabled: yes
      masked: no
      
   - name: Install NGINX on Debian
     apt:
       name: nginx
       state: present
       when: ansible_os_family == “Debian” and ansible_distribution_version == “16.04”

    - name: Install NGINX on Redhat
      yum:
        name: nginx
        state: present
        when: ansible_os_family == “RedHat” or ansible_os_family == “SUSE”
        
    - name: 'Update entry into /etc/resolv.conf'
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 10.1.250.10'
    
    - name: 'Create a new user'
      user:
        name: web_user
        uid: 1040
        group: developers
        
    - name: 'Execute a script'
      script: /tmp/install_script.sh
